const PLUKKARI = {
 "meta": {
  "kausi": "MSU2026",
  "generoitu": "2026-09-01 19:57:37",
  "lahde": "Vain arvot.xlsx / MasterLyonnit",
  "otteluita_summa": 434,
  "otteluita_datassa": 217,
  "data_vajaa": false,
  "yhteensa": {
   "vapaat": 1322,
   "vapaat_0": 979,
   "vapaat_kolmostil": 121,
   "vapaat_taydet": 59,
   "vapaat_3K": 102,
   "karpaset": 462
  },
  "keskiarvo_per_ottelu": {
   "vapaat": 3.046,
   "vapaat_0": 2.256,
   "vapaat_kolmostil": 0.279,
   "vapaat_taydet": 0.136,
   "vapaat_3K": 0.235,
   "karpaset": 1.065
  },
  "vapaat_tilanteittain": {
   "0-tilanne": 979,
   "1 -tilanne": 133,
   "1-2 -tilanne": 60,
   "1-2-3 -tilanne": 59,
   "3 -tilanne": 32,
   "2 -tilanne": 29,
   "1-3 -tilanne": 18,
   "2-3 -tilanne": 12
  },
  "selitteet": {
   "vapaat": "annetut vapaataipaleet (väärät syötöt)",
   "vapaat_0": "vapaat 0-tilanteessa — etenijä ykköspesälle",
   "vapaat_kolmostil": "vapaat kun kolmospesällä oli etenijä — vaarallisin",
   "vapaat_taydet": "vapaat täysillä pesillä (1-2-3)",
   "vapaat_3K": "rivit joilla Pesäväli = 3-K; merkitys varmistamatta",
   "karpaset": "lukkarin tekemät palot (kärpäset)"
  }
 },
 "joukkueet": {
  "AA": {
   "ottelut": 36,
   "ottelut_odotettu": 33,
   "vajaa": false,
   "nimi_pitka": "Alajärven Ankkurit",
   "vapaat": 100,
   "vapaat_per_O": 2.78,
   "vapaat_ero": -0.27,
   "vapaat_0": 63,
   "vapaat_0_per_O": 1.75,
   "vapaat_0_ero": -0.51,
   "vapaat_kolmostil": 11,
   "vapaat_kolmostil_per_O": 0.31,
   "vapaat_kolmostil_ero": 0.03,
   "vapaat_taydet": 3,
   "vapaat_taydet_per_O": 0.08,
   "vapaat_taydet_ero": -0.05,
   "vapaat_3K": 10,
   "vapaat_3K_per_O": 0.28,
   "vapaat_3K_ero": 0.04,
   "karpaset": 41,
   "karpaset_per_O": 1.14,
   "karpaset_ero": 0.07,
   "vapaat_0_osuus": 63.0
  },
  "PattU": {
   "ottelut": 36,
   "ottelut_odotettu": 33,
   "vajaa": false,
   "nimi_pitka": "Pattijoen Urheilijat",
   "vapaat": 101,
   "vapaat_per_O": 2.81,
   "vapaat_ero": -0.24,
   "vapaat_0": 79,
   "vapaat_0_per_O": 2.19,
   "vapaat_0_ero": -0.06,
   "vapaat_kolmostil": 7,
   "vapaat_kolmostil_per_O": 0.19,
   "vapaat_kolmostil_ero": -0.08,
   "vapaat_taydet": 3,
   "vapaat_taydet_per_O": 0.08,
   "vapaat_taydet_ero": -0.05,
   "vapaat_3K": 7,
   "vapaat_3K_per_O": 0.19,
   "vapaat_3K_ero": -0.04,
   "karpaset": 47,
   "karpaset_per_O": 1.31,
   "karpaset_ero": 0.24,
   "vapaat_0_osuus": 78.2
  },
  "Tahko": {
   "ottelut": 36,
   "ottelut_odotettu": 33,
   "vajaa": false,
   "nimi_pitka": "Hyvinkään Tahko",
   "vapaat": 120,
   "vapaat_per_O": 3.33,
   "vapaat_ero": 0.29,
   "vapaat_0": 82,
   "vapaat_0_per_O": 2.28,
   "vapaat_0_ero": 0.02,
   "vapaat_kolmostil": 15,
   "vapaat_kolmostil_per_O": 0.42,
   "vapaat_kolmostil_ero": 0.14,
   "vapaat_taydet": 6,
   "vapaat_taydet_per_O": 0.17,
   "vapaat_taydet_ero": 0.03,
   "vapaat_3K": 11,
   "vapaat_3K_per_O": 0.31,
   "vapaat_3K_ero": 0.07,
   "karpaset": 45,
   "karpaset_per_O": 1.25,
   "karpaset_ero": 0.19,
   "vapaat_0_osuus": 68.3
  },
  "KoU": {
   "ottelut": 36,
   "ottelut_odotettu": 33,
   "vajaa": false,
   "nimi_pitka": "Koskenkorvan Urheilijat",
   "vapaat": 171,
   "vapaat_per_O": 4.75,
   "vapaat_ero": 1.7,
   "vapaat_0": 130,
   "vapaat_0_per_O": 3.61,
   "vapaat_0_ero": 1.36,
   "vapaat_kolmostil": 18,
   "vapaat_kolmostil_per_O": 0.5,
   "vapaat_kolmostil_ero": 0.22,
   "vapaat_taydet": 11,
   "vapaat_taydet_per_O": 0.31,
   "vapaat_taydet_ero": 0.17,
   "vapaat_3K": 18,
   "vapaat_3K_per_O": 0.5,
   "vapaat_3K_ero": 0.27,
   "karpaset": 28,
   "karpaset_per_O": 0.78,
   "karpaset_ero": -0.29,
   "vapaat_0_osuus": 76.0
  },
  "IPV": {
   "ottelut": 33,
   "ottelut_odotettu": 33,
   "vajaa": false,
   "nimi_pitka": "Imatran Pallo-Veikot",
   "vapaat": 87,
   "vapaat_per_O": 2.64,
   "vapaat_ero": -0.41,
   "vapaat_0": 62,
   "vapaat_0_per_O": 1.88,
   "vapaat_0_ero": -0.38,
   "vapaat_kolmostil": 15,
   "vapaat_kolmostil_per_O": 0.45,
   "vapaat_kolmostil_ero": 0.18,
   "vapaat_taydet": 11,
   "vapaat_taydet_per_O": 0.33,
   "vapaat_taydet_ero": 0.2,
   "vapaat_3K": 8,
   "vapaat_3K_per_O": 0.24,
   "vapaat_3K_ero": 0.01,
   "karpaset": 43,
   "karpaset_per_O": 1.3,
   "karpaset_ero": 0.24,
   "vapaat_0_osuus": 71.3
  },
  "Manse": {
   "ottelut": 37,
   "ottelut_odotettu": 33,
   "vajaa": false,
   "nimi_pitka": "Manse PP",
   "vapaat": 122,
   "vapaat_per_O": 3.3,
   "vapaat_ero": 0.25,
   "vapaat_0": 93,
   "vapaat_0_per_O": 2.51,
   "vapaat_0_ero": 0.26,
   "vapaat_kolmostil": 7,
   "vapaat_kolmostil_per_O": 0.19,
   "vapaat_kolmostil_ero": -0.09,
   "vapaat_taydet": 4,
   "vapaat_taydet_per_O": 0.11,
   "vapaat_taydet_ero": -0.03,
   "vapaat_3K": 6,
   "vapaat_3K_per_O": 0.16,
   "vapaat_3K_ero": -0.07,
   "karpaset": 36,
   "karpaset_per_O": 0.97,
   "karpaset_ero": -0.09,
   "vapaat_0_osuus": 76.2
  },
  "JoMa": {
   "ottelut": 38,
   "ottelut_odotettu": 33,
   "vajaa": false,
   "nimi_pitka": "Joensuun Maila",
   "vapaat": 136,
   "vapaat_per_O": 3.58,
   "vapaat_ero": 0.53,
   "vapaat_0": 107,
   "vapaat_0_per_O": 2.82,
   "vapaat_0_ero": 0.56,
   "vapaat_kolmostil": 9,
   "vapaat_kolmostil_per_O": 0.24,
   "vapaat_kolmostil_ero": -0.04,
   "vapaat_taydet": 2,
   "vapaat_taydet_per_O": 0.05,
   "vapaat_taydet_ero": -0.08,
   "vapaat_3K": 6,
   "vapaat_3K_per_O": 0.16,
   "vapaat_3K_ero": -0.08,
   "karpaset": 36,
   "karpaset_per_O": 0.95,
   "karpaset_ero": -0.12,
   "vapaat_0_osuus": 78.7
  },
  "KeKi": {
   "ottelut": 33,
   "ottelut_odotettu": 33,
   "vajaa": false,
   "nimi_pitka": "Kempeleen Kiri",
   "vapaat": 105,
   "vapaat_per_O": 3.18,
   "vapaat_ero": 0.14,
   "vapaat_0": 75,
   "vapaat_0_per_O": 2.27,
   "vapaat_0_ero": 0.02,
   "vapaat_kolmostil": 14,
   "vapaat_kolmostil_per_O": 0.42,
   "vapaat_kolmostil_ero": 0.15,
   "vapaat_taydet": 9,
   "vapaat_taydet_per_O": 0.27,
   "vapaat_taydet_ero": 0.14,
   "vapaat_3K": 13,
   "vapaat_3K_per_O": 0.39,
   "vapaat_3K_ero": 0.16,
   "karpaset": 31,
   "karpaset_per_O": 0.94,
   "karpaset_ero": -0.13,
   "vapaat_0_osuus": 71.4
  },
  "SoJy": {
   "ottelut": 39,
   "ottelut_odotettu": 33,
   "vajaa": false,
   "nimi_pitka": "Sotkamon Jymy",
   "vapaat": 112,
   "vapaat_per_O": 2.87,
   "vapaat_ero": -0.17,
   "vapaat_0": 83,
   "vapaat_0_per_O": 2.13,
   "vapaat_0_ero": -0.13,
   "vapaat_kolmostil": 5,
   "vapaat_kolmostil_per_O": 0.13,
   "vapaat_kolmostil_ero": -0.15,
   "vapaat_taydet": 3,
   "vapaat_taydet_per_O": 0.08,
   "vapaat_taydet_ero": -0.06,
   "vapaat_3K": 4,
   "vapaat_3K_per_O": 0.1,
   "vapaat_3K_ero": -0.13,
   "karpaset": 47,
   "karpaset_per_O": 1.21,
   "karpaset_ero": 0.14,
   "vapaat_0_osuus": 74.1
  },
  "KPL": {
   "ottelut": 37,
   "ottelut_odotettu": 33,
   "vajaa": false,
   "nimi_pitka": "Kouvolan Pallonlyöjät",
   "vapaat": 108,
   "vapaat_per_O": 2.92,
   "vapaat_ero": -0.13,
   "vapaat_0": 92,
   "vapaat_0_per_O": 2.49,
   "vapaat_0_ero": 0.23,
   "vapaat_kolmostil": 6,
   "vapaat_kolmostil_per_O": 0.16,
   "vapaat_kolmostil_ero": -0.12,
   "vapaat_taydet": 1,
   "vapaat_taydet_per_O": 0.03,
   "vapaat_taydet_ero": -0.11,
   "vapaat_3K": 6,
   "vapaat_3K_per_O": 0.16,
   "vapaat_3K_ero": -0.07,
   "karpaset": 40,
   "karpaset_per_O": 1.08,
   "karpaset_ero": 0.02,
   "vapaat_0_osuus": 85.2
  },
  "KiPa": {
   "ottelut": 36,
   "ottelut_odotettu": 33,
   "vajaa": false,
   "nimi_pitka": "Kiteen Pallo",
   "vapaat": 95,
   "vapaat_per_O": 2.64,
   "vapaat_ero": -0.41,
   "vapaat_0": 68,
   "vapaat_0_per_O": 1.89,
   "vapaat_0_ero": -0.37,
   "vapaat_kolmostil": 9,
   "vapaat_kolmostil_per_O": 0.25,
   "vapaat_kolmostil_ero": -0.03,
   "vapaat_taydet": 5,
   "vapaat_taydet_per_O": 0.14,
   "vapaat_taydet_ero": 0.0,
   "vapaat_3K": 9,
   "vapaat_3K_per_O": 0.25,
   "vapaat_3K_ero": 0.02,
   "karpaset": 34,
   "karpaset_per_O": 0.94,
   "karpaset_ero": -0.12,
   "vapaat_0_osuus": 71.6
  },
  "ViVe": {
   "ottelut": 37,
   "ottelut_odotettu": 33,
   "vajaa": false,
   "nimi_pitka": "Vimpelin Veto",
   "vapaat": 65,
   "vapaat_per_O": 1.76,
   "vapaat_ero": -1.29,
   "vapaat_0": 45,
   "vapaat_0_per_O": 1.22,
   "vapaat_0_ero": -1.04,
   "vapaat_kolmostil": 5,
   "vapaat_kolmostil_per_O": 0.14,
   "vapaat_kolmostil_ero": -0.14,
   "vapaat_taydet": 1,
   "vapaat_taydet_per_O": 0.03,
   "vapaat_taydet_ero": -0.11,
   "vapaat_3K": 4,
   "vapaat_3K_per_O": 0.11,
   "vapaat_3K_ero": -0.13,
   "karpaset": 34,
   "karpaset_per_O": 0.92,
   "karpaset_ero": -0.15,
   "vapaat_0_osuus": 69.2
  }
 }
};
