const PLUKKARI = {
 "meta": {
  "kausi": "MSU2026",
  "generoitu": "2026-08-21 14:32:16",
  "lahde": "Vain arvot.xlsx / MasterLyonnit",
  "otteluita_summa": 400,
  "otteluita_datassa": 200,
  "data_vajaa": false,
  "yhteensa": {
   "vapaat": 1238,
   "vapaat_0": 918,
   "vapaat_kolmostil": 115,
   "vapaat_taydet": 56,
   "vapaat_3K": 95,
   "karpaset": 431
  },
  "keskiarvo_per_ottelu": {
   "vapaat": 3.095,
   "vapaat_0": 2.295,
   "vapaat_kolmostil": 0.287,
   "vapaat_taydet": 0.14,
   "vapaat_3K": 0.237,
   "karpaset": 1.077
  },
  "vapaat_tilanteittain": {
   "0-tilanne": 918,
   "1 -tilanne": 126,
   "1-2-3 -tilanne": 56,
   "1-2 -tilanne": 51,
   "3 -tilanne": 30,
   "2 -tilanne": 28,
   "1-3 -tilanne": 18,
   "2-3 -tilanne": 11
  },
  "selitteet": {
   "vapaat": "annetut vapaataipaleet (väärät syötöt)",
   "vapaat_0": "vapaat 0-tilanteessa — etenijä ykköspesälle",
   "vapaat_kolmostil": "vapaat kun kolmospesällä oli etenijä — vaarallisin",
   "vapaat_taydet": "vapaat täysillä pesillä (1-2-3)",
   "vapaat_3K": "rivit joilla Pesäväli = 3-K; merkitys varmistamatta",
   "karpaset": "lukkarin tekemät palot (kärpäset)"
  }
 },
 "joukkueet": {
  "AA": {
   "ottelut": 33,
   "ottelut_odotettu": 33,
   "vajaa": false,
   "nimi_pitka": "Alajärven Ankkurit",
   "vapaat": 91,
   "vapaat_per_O": 2.76,
   "vapaat_ero": -0.34,
   "vapaat_0": 58,
   "vapaat_0_per_O": 1.76,
   "vapaat_0_ero": -0.54,
   "vapaat_kolmostil": 11,
   "vapaat_kolmostil_per_O": 0.33,
   "vapaat_kolmostil_ero": 0.05,
   "vapaat_taydet": 3,
   "vapaat_taydet_per_O": 0.09,
   "vapaat_taydet_ero": -0.05,
   "vapaat_3K": 9,
   "vapaat_3K_per_O": 0.27,
   "vapaat_3K_ero": 0.04,
   "karpaset": 37,
   "karpaset_per_O": 1.12,
   "karpaset_ero": 0.04,
   "vapaat_0_osuus": 63.7
  },
  "PattU": {
   "ottelut": 34,
   "ottelut_odotettu": 33,
   "vajaa": false,
   "nimi_pitka": "Pattijoen Urheilijat",
   "vapaat": 98,
   "vapaat_per_O": 2.88,
   "vapaat_ero": -0.21,
   "vapaat_0": 77,
   "vapaat_0_per_O": 2.26,
   "vapaat_0_ero": -0.03,
   "vapaat_kolmostil": 7,
   "vapaat_kolmostil_per_O": 0.21,
   "vapaat_kolmostil_ero": -0.08,
   "vapaat_taydet": 3,
   "vapaat_taydet_per_O": 0.09,
   "vapaat_taydet_ero": -0.05,
   "vapaat_3K": 7,
   "vapaat_3K_per_O": 0.21,
   "vapaat_3K_ero": -0.03,
   "karpaset": 43,
   "karpaset_per_O": 1.26,
   "karpaset_ero": 0.19,
   "vapaat_0_osuus": 78.6
  },
  "Tahko": {
   "ottelut": 33,
   "ottelut_odotettu": 33,
   "vajaa": false,
   "nimi_pitka": "Hyvinkään Tahko",
   "vapaat": 111,
   "vapaat_per_O": 3.36,
   "vapaat_ero": 0.27,
   "vapaat_0": 74,
   "vapaat_0_per_O": 2.24,
   "vapaat_0_ero": -0.05,
   "vapaat_kolmostil": 15,
   "vapaat_kolmostil_per_O": 0.45,
   "vapaat_kolmostil_ero": 0.17,
   "vapaat_taydet": 6,
   "vapaat_taydet_per_O": 0.18,
   "vapaat_taydet_ero": 0.04,
   "vapaat_3K": 11,
   "vapaat_3K_per_O": 0.33,
   "vapaat_3K_ero": 0.1,
   "karpaset": 42,
   "karpaset_per_O": 1.27,
   "karpaset_ero": 0.2,
   "vapaat_0_osuus": 66.7
  },
  "KoU": {
   "ottelut": 33,
   "ottelut_odotettu": 33,
   "vajaa": false,
   "nimi_pitka": "Koskenkorvan Urheilijat",
   "vapaat": 161,
   "vapaat_per_O": 4.88,
   "vapaat_ero": 1.78,
   "vapaat_0": 125,
   "vapaat_0_per_O": 3.79,
   "vapaat_0_ero": 1.49,
   "vapaat_kolmostil": 14,
   "vapaat_kolmostil_per_O": 0.42,
   "vapaat_kolmostil_ero": 0.14,
   "vapaat_taydet": 9,
   "vapaat_taydet_per_O": 0.27,
   "vapaat_taydet_ero": 0.13,
   "vapaat_3K": 14,
   "vapaat_3K_per_O": 0.42,
   "vapaat_3K_ero": 0.19,
   "karpaset": 27,
   "karpaset_per_O": 0.82,
   "karpaset_ero": -0.26,
   "vapaat_0_osuus": 77.6
  },
  "IPV": {
   "ottelut": 33,
   "ottelut_odotettu": 33,
   "vajaa": false,
   "nimi_pitka": "Imatran Pallo-Veikot",
   "vapaat": 87,
   "vapaat_per_O": 2.64,
   "vapaat_ero": -0.46,
   "vapaat_0": 62,
   "vapaat_0_per_O": 1.88,
   "vapaat_0_ero": -0.42,
   "vapaat_kolmostil": 15,
   "vapaat_kolmostil_per_O": 0.45,
   "vapaat_kolmostil_ero": 0.17,
   "vapaat_taydet": 11,
   "vapaat_taydet_per_O": 0.33,
   "vapaat_taydet_ero": 0.19,
   "vapaat_3K": 8,
   "vapaat_3K_per_O": 0.24,
   "vapaat_3K_ero": 0.01,
   "karpaset": 43,
   "karpaset_per_O": 1.3,
   "karpaset_ero": 0.23,
   "vapaat_0_osuus": 71.3
  },
  "Manse": {
   "ottelut": 33,
   "ottelut_odotettu": 33,
   "vajaa": false,
   "nimi_pitka": "Manse PP",
   "vapaat": 111,
   "vapaat_per_O": 3.36,
   "vapaat_ero": 0.27,
   "vapaat_0": 85,
   "vapaat_0_per_O": 2.58,
   "vapaat_0_ero": 0.28,
   "vapaat_kolmostil": 7,
   "vapaat_kolmostil_per_O": 0.21,
   "vapaat_kolmostil_ero": -0.07,
   "vapaat_taydet": 4,
   "vapaat_taydet_per_O": 0.12,
   "vapaat_taydet_ero": -0.02,
   "vapaat_3K": 6,
   "vapaat_3K_per_O": 0.18,
   "vapaat_3K_ero": -0.06,
   "karpaset": 32,
   "karpaset_per_O": 0.97,
   "karpaset_ero": -0.11,
   "vapaat_0_osuus": 76.6
  },
  "JoMa": {
   "ottelut": 34,
   "ottelut_odotettu": 33,
   "vajaa": false,
   "nimi_pitka": "Joensuun Maila",
   "vapaat": 125,
   "vapaat_per_O": 3.68,
   "vapaat_ero": 0.58,
   "vapaat_0": 99,
   "vapaat_0_per_O": 2.91,
   "vapaat_0_ero": 0.62,
   "vapaat_kolmostil": 9,
   "vapaat_kolmostil_per_O": 0.26,
   "vapaat_kolmostil_ero": -0.02,
   "vapaat_taydet": 2,
   "vapaat_taydet_per_O": 0.06,
   "vapaat_taydet_ero": -0.08,
   "vapaat_3K": 6,
   "vapaat_3K_per_O": 0.18,
   "vapaat_3K_ero": -0.06,
   "karpaset": 34,
   "karpaset_per_O": 1.0,
   "karpaset_ero": -0.08,
   "vapaat_0_osuus": 79.2
  },
  "KeKi": {
   "ottelut": 33,
   "ottelut_odotettu": 33,
   "vajaa": false,
   "nimi_pitka": "Kempeleen Kiri",
   "vapaat": 105,
   "vapaat_per_O": 3.18,
   "vapaat_ero": 0.09,
   "vapaat_0": 75,
   "vapaat_0_per_O": 2.27,
   "vapaat_0_ero": -0.02,
   "vapaat_kolmostil": 14,
   "vapaat_kolmostil_per_O": 0.42,
   "vapaat_kolmostil_ero": 0.14,
   "vapaat_taydet": 9,
   "vapaat_taydet_per_O": 0.27,
   "vapaat_taydet_ero": 0.13,
   "vapaat_3K": 13,
   "vapaat_3K_per_O": 0.39,
   "vapaat_3K_ero": 0.16,
   "karpaset": 31,
   "karpaset_per_O": 0.94,
   "karpaset_ero": -0.14,
   "vapaat_0_osuus": 71.4
  },
  "SoJy": {
   "ottelut": 34,
   "ottelut_odotettu": 33,
   "vajaa": false,
   "nimi_pitka": "Sotkamon Jymy",
   "vapaat": 101,
   "vapaat_per_O": 2.97,
   "vapaat_ero": -0.12,
   "vapaat_0": 74,
   "vapaat_0_per_O": 2.18,
   "vapaat_0_ero": -0.12,
   "vapaat_kolmostil": 5,
   "vapaat_kolmostil_per_O": 0.15,
   "vapaat_kolmostil_ero": -0.14,
   "vapaat_taydet": 3,
   "vapaat_taydet_per_O": 0.09,
   "vapaat_taydet_ero": -0.05,
   "vapaat_3K": 4,
   "vapaat_3K_per_O": 0.12,
   "vapaat_3K_ero": -0.12,
   "karpaset": 40,
   "karpaset_per_O": 1.18,
   "karpaset_ero": 0.1,
   "vapaat_0_osuus": 73.3
  },
  "KPL": {
   "ottelut": 33,
   "ottelut_odotettu": 33,
   "vajaa": false,
   "nimi_pitka": "Kouvolan Pallonlyöjät",
   "vapaat": 99,
   "vapaat_per_O": 3.0,
   "vapaat_ero": -0.1,
   "vapaat_0": 84,
   "vapaat_0_per_O": 2.55,
   "vapaat_0_ero": 0.25,
   "vapaat_kolmostil": 6,
   "vapaat_kolmostil_per_O": 0.18,
   "vapaat_kolmostil_ero": -0.11,
   "vapaat_taydet": 1,
   "vapaat_taydet_per_O": 0.03,
   "vapaat_taydet_ero": -0.11,
   "vapaat_3K": 6,
   "vapaat_3K_per_O": 0.18,
   "vapaat_3K_ero": -0.06,
   "karpaset": 37,
   "karpaset_per_O": 1.12,
   "karpaset_ero": 0.04,
   "vapaat_0_osuus": 84.8
  },
  "KiPa": {
   "ottelut": 33,
   "ottelut_odotettu": 33,
   "vajaa": false,
   "nimi_pitka": "Kiteen Pallo",
   "vapaat": 89,
   "vapaat_per_O": 2.7,
   "vapaat_ero": -0.4,
   "vapaat_0": 64,
   "vapaat_0_per_O": 1.94,
   "vapaat_0_ero": -0.36,
   "vapaat_kolmostil": 7,
   "vapaat_kolmostil_per_O": 0.21,
   "vapaat_kolmostil_ero": -0.07,
   "vapaat_taydet": 4,
   "vapaat_taydet_per_O": 0.12,
   "vapaat_taydet_ero": -0.02,
   "vapaat_3K": 7,
   "vapaat_3K_per_O": 0.21,
   "vapaat_3K_ero": -0.02,
   "karpaset": 34,
   "karpaset_per_O": 1.03,
   "karpaset_ero": -0.05,
   "vapaat_0_osuus": 71.9
  },
  "ViVe": {
   "ottelut": 34,
   "ottelut_odotettu": 33,
   "vajaa": false,
   "nimi_pitka": "Vimpelin Veto",
   "vapaat": 60,
   "vapaat_per_O": 1.76,
   "vapaat_ero": -1.33,
   "vapaat_0": 41,
   "vapaat_0_per_O": 1.21,
   "vapaat_0_ero": -1.09,
   "vapaat_kolmostil": 5,
   "vapaat_kolmostil_per_O": 0.15,
   "vapaat_kolmostil_ero": -0.14,
   "vapaat_taydet": 1,
   "vapaat_taydet_per_O": 0.03,
   "vapaat_taydet_ero": -0.11,
   "vapaat_3K": 4,
   "vapaat_3K_per_O": 0.12,
   "vapaat_3K_ero": -0.12,
   "karpaset": 31,
   "karpaset_per_O": 0.91,
   "karpaset_ero": -0.17,
   "vapaat_0_osuus": 68.3
  }
 }
};
